# Generated by Django 4.1.5 on 2023-01-18 16:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=1, max_digits=2)),
                ('width', models.DecimalField(decimal_places=1, max_digits=2)),
                ('subject', models.CharField(choices=[('Abstract', 'Abstract'), ('Landscape', 'Landscape'), ('Animal', 'Animal'), ('Other', 'Other')], default='Abstract', max_length=50)),
                ('medium', models.CharField(choices=[('Acrylic', 'Acrylic'), ('Oil', 'Oil'), ('Watercolor', 'Watercolor')], default='Acrylic', max_length=50)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artists.artist')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dealers.dealer')),
            ],
        ),
    ]
