# Generated by Django 4.1.5 on 2023-01-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='advert',
            name='width',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
