# Generated by Django 4.1.5 on 2023-01-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_alter_advert_height_alter_advert_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='medium',
            field=models.CharField(choices=[('Acrylic', 'Acrylic'), ('Oil', 'Oil'), ('Watercolor', 'Watercolor'), ('Other', 'Other')], default='Acrylic', max_length=50),
        ),
    ]
