# Generated by Django 4.1.5 on 2023-01-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_alter_advert_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='subject',
            field=models.CharField(choices=[('Abstract', 'Abstract'), ('People', 'People'), ('Landscape', 'Landscape'), ('Animal', 'Animal'), ('Other', 'Other')], default='Abstract', max_length=50),
        ),
    ]
